// <auto-generated />
using System;
using MVCControlStation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCControlStation.Migrations
{
    [DbContext(typeof(MVCControlStationContext))]
    partial class MVCControlStationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MVCControlStation.Models.FaultControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ActivEnginer");

                    b.Property<DateTime>("StartService");

                    b.Property<DateTime>("StopOperacao");

                    b.Property<int>("Week");

                    b.HasKey("Id");

                    b.ToTable("FaultControl");
                });

            modelBuilder.Entity("MVCControlStation.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FaultControlId");

                    b.Property<int>("NameStation");

                    b.HasKey("Id");

                    b.HasIndex("FaultControlId");

                    b.ToTable("Station");
                });

            modelBuilder.Entity("MVCControlStation.Models.TestTecnian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FaultControlId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("FaultControlId");

                    b.ToTable("TestTecnian");
                });

            modelBuilder.Entity("MVCControlStation.Models.Station", b =>
                {
                    b.HasOne("MVCControlStation.Models.FaultControl")
                        .WithMany("stations")
                        .HasForeignKey("FaultControlId");
                });

            modelBuilder.Entity("MVCControlStation.Models.TestTecnian", b =>
                {
                    b.HasOne("MVCControlStation.Models.FaultControl")
                        .WithMany("tecnians")
                        .HasForeignKey("FaultControlId");
                });
#pragma warning restore 612, 618
        }
    }
}
